services:
  # AIO Search Tool - Streamlit Web Application
  - type: web
    name: aio-search-tool
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run web_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --browser.gatherUsageStats false"
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: AIRTOP_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false 